### ISSUE TITLE
update middleware page

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster-website#10]
- top of middleware page says `scServer`, examples say `wsServer`. Should all say `scServer`.
- Nothing mentions the interface for `req` (`data, waitForAuth, socket`...)

will PR when i finish the sprint & find more stuff as I read the guide with fresh, forgetful eyes :smile:

**Comment by jondubois** [comment]
@mattkrick If you look under `subscribe` method http://socketcluster.io/#!/docs/api-scsocket-client - It has info about waitFroAuth, but yeah it doesn't currently show the `data` option.

Feel free to make a PR if you get the time.

**Comment by jondubois** [comment]
@mattkrick Thanks, should be fixed now... Finally ;p
https://socketcluster.io/#!/docs/middleware-and-authorization
