### ISSUE TITLE
reference to nonexisting method agServer.addMiddleware

### ISSUE THREAD

**Issue by damianb** [SocketCluster/socketcluster-website#23]
https://socketcluster.io/docs/authentication/#verify-and-use-the-jwt-token

```
agServer.addMiddleware(agServer.MIDDLEWARE_INBOUND, async (middlewareStream) => {
  for await (let action of middlewareStream) {
```

Not sure what that needs to be.  My best guess on context is `.setMiddleware`?

**Comment by jondubois** [comment]
Fixed. Thanks for reporting.
