### ISSUE TITLE
Links to Release notes of older versions are broken

### ISSUE THREAD

**Issue by mauritslamers** [SocketCluster/socketcluster-website#33]
When trying to locate the release notes of the previous versions of socketcluster, I ran into some broken links:

v15.0.6 points to https://github.com/SocketCluster/socketcluster-website/releases/tag/v15.0.6 and v14.4.2 points to https://github.com/SocketCluster/socketcluster-website/releases/tag/v14.4.2 but there is nothing there.

This is partly because they point to the releases tags of the socketcluster-website repository where there are none, but even when they would point to the socketcluster repository, it would not work as that v14.4.2 version is not in the releases.

**Comment by MegaGM** [comment]
Thank you @mauritslamers ! 
fixed in https://github.com/SocketCluster/socketcluster-website/commit/ddb9b4e733fac04fd061299067a2edb4bb6ddc3f
